version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natega2026_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
